INSERT INTO public.genre (genre_id, genre_title) VALUES (1, 'Classical');
INSERT INTO public.genre (genre_id, genre_title) VALUES (2, 'Hip-Hop');
INSERT INTO public.genre (genre_id, genre_title) VALUES (3, 'Rap');
INSERT INTO public.genre (genre_id, genre_title) VALUES (4, 'Country');
INSERT INTO public.genre (genre_id, genre_title) VALUES (5, 'Folk');
INSERT INTO public.genre (genre_id, genre_title) VALUES (6, 'Rock');
INSERT INTO public.genre (genre_id, genre_title) VALUES (7, 'Pop');
INSERT INTO public.genre (genre_id, genre_title) VALUES (8, 'Jazz');
INSERT INTO public.genre (genre_id, genre_title) VALUES (9, 'Metal');
INSERT INTO public.genre (genre_id, genre_title) VALUES (10, 'Punk');
INSERT INTO public.genre (genre_id, genre_title) VALUES (11, 'Instrumental');
INSERT INTO public.genre (genre_id, genre_title) VALUES (12, 'Acapella');
INSERT INTO public.genre (genre_id, genre_title) VALUES (13, 'Dubstep');
INSERT INTO public.genre (genre_id, genre_title) VALUES (14, 'Blues');
INSERT INTO public.genre (genre_id, genre_title) VALUES (15, 'Ska');
INSERT INTO public.genre (genre_id, genre_title) VALUES (16, 'New Age');
INSERT INTO public.genre (genre_id, genre_title) VALUES (17, 'Disco');
INSERT INTO public.genre (genre_id, genre_title) VALUES (18, 'Soul');
INSERT INTO public.genre (genre_id, genre_title) VALUES (19, 'Soundtrack');
INSERT INTO public.genre (genre_id, genre_title) VALUES (20, 'Grunge');
INSERT INTO public.genre (genre_id, genre_title) VALUES (21, 'Alternative Rock');
INSERT INTO public.genre (genre_id, genre_title) VALUES (22, 'Indie');
INSERT INTO public.genre (genre_id, genre_title) VALUES (23, 'Bluegrass');
INSERT INTO public.genre (genre_id, genre_title) VALUES (24, 'Techno');
INSERT INTO public.genre (genre_id, genre_title) VALUES (25, 'Musical Theater');
INSERT INTO public.genre (genre_id, genre_title) VALUES (26, 'Reggae');
INSERT INTO public.genre (genre_id, genre_title) VALUES (27, 'Electronic Dance');
INSERT INTO public.genre (genre_id, genre_title) VALUES (28, 'Art Music');
INSERT INTO public.genre (genre_id, genre_title) VALUES (29, 'R&B');
INSERT INTO public.genre (genre_id, genre_title) VALUES (0, 'Yodelling');
INSERT INTO public.genre (genre_id, genre_title) VALUES (31, 'Funk');